project:
  type: website
  output-dir: _Website
website:
  title: "Helen Guo's Website"
  navbar:
    background: "#f1f1f1"
    foreground: "#164a58"
    left:
      - href: index.qmd
        text: Home
      - href: About.qmd
        text: About Me
      - href: Example Analysis.qmd
        text: Example Analysis
